# Generated by Django 2.2.14 on 2020-07-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.IntegerField(help_text='크로스핏 박스 번호', primary_key=True, serialize=False, unique=True)),
                ('boxname', models.CharField(help_text='크로스핏 박스 이름', max_length=150)),
                ('boxwebsite', models.URLField(help_text='크로스핏 박스 URL', max_length=255)),
                ('boxaddress', models.CharField(help_text='크로스핏 박스 주소', max_length=255)),
                ('boxcity', models.CharField(help_text='크로스핏 박스 도시', max_length=100)),
                ('boxcountry', models.CharField(help_text='크로스핏 박스 나라', max_length=100)),
                ('boxcfkids', models.BooleanField()),
                ('boxzipcode', models.IntegerField(help_text='zip_code')),
                ('boxphone', models.CharField(help_text='전화번호', max_length=100)),
                ('boxlat', models.FloatField(help_text='위도')),
                ('boxlng', models.FloatField(help_text='경도')),
            ],
        ),
    ]
