# Generated by Django 2.2.14 on 2020-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='boxstate',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
