# Generated by Django 2.2.14 on 2020-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_boxstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='boxzipcode',
            field=models.CharField(help_text='zip_code', max_length=100),
        ),
    ]
