# Generated by Django 2.2.14 on 2020-07-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coachName', models.CharField(help_text='코치 이름', max_length=100)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boxes.Box')),
            ],
        ),
    ]
